name: Templify Vue CI

on:
  push:
    branches: ["feature/AZDmEw2i-frontend-cicd"]
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

permissions:
  contents: read

jobs:
  build_and_dockerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract release version
        id: version
        run: |
          # HEAD가 마지막 merge commit인지 확인
          if git show --no-patch --format=%P | grep -q ' '; then
            # merge commit으로부터 메세지 추출
            COMMIT_MSG=$(git log --format=%B -n 1 HEAD)
            echo "Merge commit detected: $COMMIT_MSG"
          else
            # 가장 최근 non-merge commit을 추출
            COMMIT_MSG=$(git log --format=%B -n 1)
            echo "Regular commit detected: $COMMIT_MSG"
          fi

          # 브랜치 명명 규칙으로부터 버전 추출
          VERSION=$(echo "$COMMIT_MSG" | grep -oP "Merge branch 'release/\K[0-9]+(\.[0-9]+){2,}" || true)

          # Merge commit이 아닌 경우일 때 버전 추출을 위한 예외 처리
          if [ -z "$VERSION" ]; then
            VERSION=$(echo "$GITHUB_REF" | grep -oP "release/\K[0-9]+(\.[0-9]+){2,}" || true)
          fi

          # 최종 버전 확인 및 클렌징
          if [ -n "$VERSION" ]; then
            VERSION=$(echo "$VERSION" | tr -d ' ' | tr '/' '-' | sed 's/[^a-zA-Z0-9.-]//g' | cut -c 1-128)
          else
            VERSION=$(git rev-parse --short=8 HEAD)
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/templify-vue:${{ steps.version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/templify-vue:latest
